<?php
/**
 * Invoice Ninja (https://invoiceninja.com).
 *
 * @link https://github.com/invoiceninja/invoiceninja source repository
 *
 * @copyright Copyright (c) 2024. Invoice Ninja LLC (https://invoiceninja.com)
 *
 * @license https://www.elastic.co/licensing/elastic-license
 */

namespace InvoiceNinja\EInvoice\Standards\Peppol;

class SchemeId
{

    public array $schemes = [
        "0002" =>	"System Information et Repertoire des Entreprise et des Etablissements: SIRENE",
        "0007" =>	"Organisationsnummer (Swedish legal entities)",
        "0009" =>	"SIRET-CODE",
        "0037" =>	"LY-tunnus",
        "0060" =>	"Data Universal Numbering System (D-U-N-S Number)",
        "0088" =>	"EAN Location Code",
        "0096" =>	"DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)",
        "0097" =>	"FTI - Ediforum Italia, (EDIRA compliant)",
        "0106" =>	"Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)",
        "0130" =>	"Directorates of the European Commission",
        "0135" =>	"SIA Object Identifiers",
        "0142" =>	"SECETI Object Identifiers",
        "0151" =>	"Australian Business Number (ABN) Scheme",
        "0183" =>	"Numéro d'identification suisse des enterprises (IDE), Swiss Unique Business Identification Number (UIDB)",
        "0184" =>	"DIGSTORG",
        "0188" =>	"Corporate Number of The Social Security and Tax Number System",
        "0190" =>	"Dutch Originator's Identification Number",
        "0191" =>	"Centre of Registers and Information Systems of the Ministry of Justice",
        "0192" =>	"Enhetsregisteret ved Bronnoysundregisterne",
        "0193" =>	"UBL.BE party identifier",
        "0195" =>	"Singapore UEN identifier",
        "0196" =>	"Kennitala - Iceland legal id for individuals and legal entities",
        "0198" =>	"ERSTORG",
        "0199" =>	"Legal Entity Identifier (LEI)",
        "0200" =>	"Legal entity code (Lithuania)",
        "0201" =>	"Codice Univoco Unità Organizzativa iPA",
        "0202" =>	"Indirizzo di Posta Elettronica Certificata",
        "0204" =>	"Leitweg-ID",
        "0208" =>	"Numero d'entreprise / ondernemingsnummer / Unternehmensnummer",
        "0209" =>	"GS1 identification keys",
        "0210" =>	"CODICE FISCALE",
        "0211" =>	"PARTITA IVA",
        "0212" =>	"Finnish Organization Identifier",
        "0213" =>	"Finnish Organization Value Add Tax Identifier",
        "0215" =>	"Net service ID",
        "0216" =>	"OVTcode",
        "0217" =>	"The Netherlands Chamber of Commerce and Industry establishment number",
        "0221" =>	"The registered number of the qualified invoice issuer (Japan)",
        "0230" =>	"National e-Invoicing Framework (Malaysia)",
        "9901" =>	"Danish Ministry of the Interior and Health",
        "9910" =>	"Hungary VAT number",
        "9913" =>	"Business Registers Network",
        "9914" =>	"Österreichische Umsatzsteuer-Identifikationsnummer",
        "9915" =>	"Österreichisches Verwaltungs bzw. Organisationskennzeichen",
        "9918" =>	"SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T",
        "9919" =>	"Kennziffer des Unternehmensregisters",
        "9920" =>	"Agencia Española de Administración Tributaria",
        "9922" =>	"Andorra VAT number",
        "9923" =>	"Albania VAT number",
        "9924" =>	"Bosnia and Herzegovina VAT number",
        "9925" =>	"Belgium VAT number",
        "9926" =>	"Bulgaria VAT number",
        "9927" =>	"Switzerland VAT number",
        "9928" =>	"Cyprus VAT number",
        "9929" =>	"Czech Republic VAT number",
        "9930" =>	"Germany VAT number",
        "9931" =>	"Estonia VAT number",
        "9932" =>	"United Kingdom VAT number",
        "9933" =>	"Greece VAT number",
        "9934" =>	"Croatia VAT number",
        "9935" =>	"Ireland VAT number",
        "9936" =>	"Liechtenstein VAT number",
        "9937" =>	"Lithuania VAT number",
        "9938" =>	"Luxemburg VAT number",
        "9939" =>	"Latvia VAT number",
        "9940" =>	"Monaco VAT number",
        "9941" =>	"Montenegro VAT number",
        "9942" =>	"Macedonia, the former Yugoslav Republic of VAT number",
        "9943" =>	"Malta VAT number",
        "9944" =>	"Netherlands VAT number",
        "9945" =>	"Poland VAT number",
        "9946" =>	"Portugal VAT number",
        "9947" =>	"Romania VAT number",
        "9948" =>	"Serbia VAT number",
        "9949" =>	"Slovenia VAT number",
        "9950" =>	"Slovakia VAT number",
        "9951" =>	"San Marino VAT number",
        "9952" =>	"Turkey VAT number",
        "9953" =>	"Holy See (Vatican City State) VAT number",
        "9957" =>	"French VAT number",
        "9959" =>	"Employer Identification Number (EIN, USA)",
    ];

        public array $schemeIDs = [
            "0002" => "FR", // France
            "0007" => "SE", // Sweden
            "0009" => "FR", // France
            "0037" => "LT", // Lithuania
            "0060" => "ZZ", // Global (D-U-N-S Number)
            "0088" => "ZZ", // Global (EAN Location Code)
            "0096" => "DK", // Denmark
            "0097" => "IT", // Italy
            "0106" => "NL", // Netherlands
            "0130" => "EU", // European Union
            "0135" => "ZZ", // Global (SIA Object Identifiers)
            "0142" => "ZZ", // Global (SECETI Object Identifiers)
            "0151" => "AU", // Australia
            "0183" => "CH", // Switzerland
            "0184" => "DK", // Denmark
            "0188" => "ZZ", // Global
            "0190" => "NL", // Netherlands
            "0191" => "EE", // Estonia
            "0192" => "NO", // Norway
            "0193" => "EE", // Estonia
            "0195" => "SG", // Singapore
            "0196" => "IS", // Iceland
            "0198" => "EE", // Estonia
            "0199" => "ZZ", // Global (Legal Entity Identifier)
            "0200" => "LT", // Lithuania
            "0201" => "IT", // Italy
            "0202" => "IT", // Italy
            "0204" => "DE", // Germany
            "0208" => "EU", // European Union
            "0209" => "IT", // Italy
            "0210" => "IT", // Italy
            "0211" => "IT", // Italy
            "0212" => "FI", // Finland
            "0213" => "FI", // Finland
            "0215" => "FI", // Finland
            "0216" => "FI", // Finland
            "0218" => "LV", // Latvia
            "0221" => "JP", // Japan
            "0230" => "MY", // Malaysia
            "9901" => "DK", // Denmark
            "9910" => "HU", // Hungary
            "9913" => "ZZ", // Global
            "9914" => "ZZ", // Global
            "9915" => "AT", // Austria
            "9918" => "ZZ", // Global
            "9919" => "DE", // Germany
            "9920" => "ES", // Spain
            "9922" => "AD", // Andorra
            "9923" => "AL", // Albania
            "9924" => "BA", // Bosnia and Herzegovina
            "9925" => "BE", // Belgium
            "9926" => "BG", // Bulgaria
            "9927" => "CH", // Switzerland
            "9928" => "CY", // Cyprus
            "9929" => "CZ", // Czech Republic
            "9930" => "DE", // Germany
            "9931" => "EE", // Estonia
            "9932" => "GB", // United Kingdom
            "9933" => "GR", // Greece
            "9934" => "HR", // Croatia
            "9935" => "IE", // Ireland
            "9936" => "LI", // Liechtenstein
            "9937" => "LT", // Lithuania
            "9938" => "LU", // Luxembourg
            "9939" => "LV", // Latvia
            "9940" => "MC", // Monaco
            "9941" => "ME", // Montenegro
            "9942" => "MK", // North Macedonia
            "9943" => "MT", // Malta
            "9944" => "NL", // Netherlands
            "9945" => "PL", // Poland
            "9946" => "PT", // Portugal
            "9947" => "RO", // Romania
            "9948" => "RS", // Serbia
            "9949" => "SI", // Slovenia
            "9950" => "SK", // Slovakia
            "9951" => "SM", // San Marino
            "9952" => "TR", // Turkey
            "9953" => "VA", // Vatican City
            "9957" => "FR", // France
            "9959" => "US", // United States
        ];

        private array $iso_3166_2 = [
            "AF" => "Afghanistan",
            "AL" => "Albania",
            "AQ" => "Antarctica",
            "DZ" => "Algeria",
            "AS" => "American Samoa",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AG" => "Antigua and Barbuda",
            "AZ" => "Azerbaijan",
            "AR" => "Argentina",
            "AU" => "Australia",
            "AT" => "Austria",
            "BS" => "Bahamas",
            "BH" => "Bahrain",
            "BD" => "Bangladesh",
            "AM" => "Armenia",
            "BB" => "Barbados",
            "BE" => "Belgium",
            "BM" => "Bermuda",
            "BT" => "Bhutan",
            "BO" => "Bolivia, Plurinational State of",
            "BA" => "Bosnia and Herzegovina",
            "BW" => "Botswana",
            "BV" => "Bouvet Island",
            "BR" => "Brazil",
            "BZ" => "Belize",
            "IO" => "British Indian Ocean Territory",
            "SB" => "Solomon Islands",
            "VG" => "Virgin Islands, British",
            "BN" => "Brunei Darussalam",
            "BG" => "Bulgaria",
            "MM" => "Myanmar",
            "BI" => "Burundi",
            "BY" => "Belarus",
            "KH" => "Cambodia",
            "CM" => "Cameroon",
            "CA" => "Canada",
            "CV" => "Cape Verde",
            "KY" => "Cayman Islands",
            "CF" => "Central African Republic",
            "LK" => "Sri Lanka",
            "TD" => "Chad",
            "CL" => "Chile",
            "CN" => "China",
            "TW" => "Taiwan, Province of China",
            "CX" => "Christmas Island",
            "CC" => "Cocos (Keeling) Islands",
            "CO" => "Colombia",
            "KM" => "Comoros",
            "YT" => "Mayotte",
            "CG" => "Congo",
            "CD" => "Congo, the Democratic Republic of the",
            "CK" => "Cook Islands",
            "CR" => "Costa Rica",
            "HR" => "Croatia",
            "CU" => "Cuba",
            "CY" => "Cyprus",
            "CZ" => "Czech Republic",
            "BJ" => "Benin",
            "DK" => "Denmark",
            "DM" => "Dominica",
            "DO" => "Dominican Republic",
            "EC" => "Ecuador",
            "SV" => "El Salvador",
            "GQ" => "Equatorial Guinea",
            "ET" => "Ethiopia",
            "ER" => "Eritrea",
            "EE" => "Estonia",
            "FO" => "Faroe Islands",
            "FK" => "Falkland Islands (Malvinas)",
            "GS" => "South Georgia and the South Sandwich Islands",
            "FJ" => "Fiji",
            "FI" => "Finland",
            "AX" => "Åland Islands",
            "FR" => "France",
            "GF" => "French Guiana",
            "PF" => "French Polynesia",
            "TF" => "French Southern Territories",
            "DJ" => "Djibouti",
            "GA" => "Gabon",
            "GE" => "Georgia",
            "GM" => "Gambia",
            "PS" => "Palestine",
            "DE" => "Germany",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "KI" => "Kiribati",
            "GR" => "Greece",
            "GL" => "Greenland",
            "GD" => "Grenada",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GN" => "Guinea",
            "GY" => "Guyana",
            "HT" => "Haiti",
            "HM" => "Heard Island and McDonald Islands",
            "VA" => "Holy See (Vatican City State)",
            "HN" => "Honduras",
            "HK" => "Hong Kong",
            "HU" => "Hungary",
            "IS" => "Iceland",
            "IN" => "India",
            "ID" => "Indonesia",
            "IR" => "Iran, Islamic Republic of",
            "IQ" => "Iraq",
            "IE" => "Ireland",
            "IL" => "Israel",
            "IT" => "Italy",
            "CI" => "Côte d'Ivoire",
            "JM" => "Jamaica",
            "JP" => "Japan",
            "KZ" => "Kazakhstan",
            "JO" => "Jordan",
            "KE" => "Kenya",
            "KP" => "Korea, Democratic People's Republic of",
            "KR" => "Korea, Republic of",
            "KW" => "Kuwait",
            "KG" => "Kyrgyzstan",
            "LA" => "Lao People's Democratic Republic",
            "LB" => "Lebanon",
            "LS" => "Lesotho",
            "LV" => "Latvia",
            "LR" => "Liberia",
            "LY" => "Libya",
            "LI" => "Liechtenstein",
            "LT" => "Lithuania",
            "LU" => "Luxembourg",
            "MO" => "Macao",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "MY" => "Malaysia",
            "MV" => "Maldives",
            "ML" => "Mali",
            "MT" => "Malta",
            "MQ" => "Martinique",
            "MR" => "Mauritania",
            "MU" => "Mauritius",
            "MX" => "Mexico",
            "MC" => "Monaco",
            "MN" => "Mongolia",
            "MD" => "Moldova, Republic of",
            "ME" => "Montenegro",
            "MS" => "Montserrat",
            "MA" => "Morocco",
            "MZ" => "Mozambique",
            "OM" => "Oman",
            "NA" => "Namibia",
            "NR" => "Nauru",
            "NP" => "Nepal",
            "NL" => "Netherlands",
            "CW" => "Curaçao",
            "AW" => "Aruba",
            "SX" => "Sint Maarten (Dutch part)",
            "BQ" => "Bonaire, Sint Eustatius and Saba",
            "NC" => "New Caledonia",
            "VU" => "Vanuatu",
            "NZ" => "New Zealand",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigeria",
            "NU" => "Niue",
            "NF" => "Norfolk Island",
            "NO" => "Norway",
            "MP" => "Northern Mariana Islands",
            "UM" => "United States Minor Outlying Islands",
            "FM" => "Micronesia, Federated States of",
            "MH" => "Marshall Islands",
            "PW" => "Palau",
            "PK" => "Pakistan",
            "PA" => "Panama",
            "PG" => "Papua New Guinea",
            "PY" => "Paraguay",
            "PE" => "Peru",
            "PH" => "Philippines",
            "PN" => "Pitcairn",
            "PL" => "Poland",
            "PT" => "Portugal",
            "GW" => "Guinea-Bissau",
            "TL" => "Timor-Leste",
            "PR" => "Puerto Rico",
            "QA" => "Qatar",
            "RE" => "Réunion",
            "RO" => "Romania",
            "RU" => "Russian Federation",
            "RW" => "Rwanda",
            "BL" => "Saint Barthélemy",
            "SH" => "Saint Helena, Ascension and Tristan da Cunha",
            "KN" => "Saint Kitts and Nevis",
            "AI" => "Anguilla",
            "LC" => "Saint Lucia",
            "MF" => "Saint Martin (French part)",
            "PM" => "Saint Pierre and Miquelon",
            "VC" => "Saint Vincent and the Grenadines",
            "SM" => "San Marino",
            "ST" => "Sao Tome and Principe",
            "SA" => "Saudi Arabia",
            "SN" => "Senegal",
            "RS" => "Serbia",
            "SC" => "Seychelles",
            "SL" => "Sierra Leone",
            "SG" => "Singapore",
            "SK" => "Slovakia",
            "VN" => "Viet Nam",
            "SI" => "Slovenia",
            "SO" => "Somalia",
            "ZA" => "South Africa",
            "ZW" => "Zimbabwe",
            "ES" => "Spain",
            "SS" => "South Sudan",
            "SD" => "Sudan",
            "EH" => "Western Sahara",
            "SR" => "Suriname",
            "SJ" => "Svalbard and Jan Mayen",
            "SZ" => "Swaziland",
            "SE" => "Sweden",
            "CH" => "Switzerland",
            "SY" => "Syrian Arab Republic",
            "TJ" => "Tajikistan",
            "TH" => "Thailand",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinidad and Tobago",
            "AE" => "United Arab Emirates",
            "TN" => "Tunisia",
            "TR" => "Turkey",
            "TM" => "Turkmenistan",
            "TC" => "Turks and Caicos Islands",
            "TV" => "Tuvalu",
            "UG" => "Uganda",
            "UA" => "Ukraine",
            "MK" => "Macedonia, the former Yugoslav Republic of",
            "EG" => "Egypt",
            "GB" => "United Kingdom",
            "GG" => "Guernsey",
            "JE" => "Jersey",
            "IM" => "Isle of Man",
            "TZ" => "Tanzania, United Republic of",
            "US" => "United States",
            "VI" => "Virgin Islands, U.S.",
            "BF" => "Burkina Faso",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VE" => "Venezuela, Bolivarian Republic of",
            "WF" => "Wallis and Futuna",
            "WS" => "Samoa",
            "YE" => "Yemen",
            "ZM" => "Zambia",
        ];

    public function resolveForCountry(string $iso_3166_2): array
    {
        $keys = array_keys($this->schemeIDs, $iso_3166_2);
        return array_intersect_key($this->schemes, array_flip($keys)) ?? []; // @phpstan-ignore-line
    }
}